local:
  frontend: http://localhost:50300
  test-rp: http://localhost:50130/test-rp
  idps:
    Stub Country: http://localhost:50140/eidas/stub-country/
    Stub Idp Demo One: http://localhost:50140/stub-idp-demo-one/
    Stub Idp Demo Two: http://localhost:50140/stub-idp-demo-two/
    Stub Idp Disconnected: http://localhost:50140/stub-idp-disconnected/

docker-local:
  frontend: http://frontend
  test-rp: http://test-rp/test-rp
  idps:
    Stub Country: http://stub-idp/eidas/stub-country/
    Stub Idp Demo One: http://stub-idp/stub-idp-demo-one/
    Stub Idp Demo Two: http://stub-idp/stub-idp-demo-two/
    Stub Idp Disconnected: http://stub-idp/stub-idp-disconnected/

staging:
  frontend: https://www.staging.signin.service.gov.uk
  test-rp: https://test-rp-staging.cloudapps.digital/test-rp
  idps:
    Stub Country: https://stub-idp-staging.cloudapps.digital/eidas/stub-country/
    Stub Idp Demo One: https://stub-idp-staging.cloudapps.digital/stub-idp-demo-one/
    Stub Idp Demo Two: https://stub-idp-staging.cloudapps.digital/stub-idp-demo-two/
    Stub Idp Disconnected: https://stub-idp-staging.cloudapps.digital/stub-idp-disconnected/

integration:
  frontend: https://www.integration.signin.service.gov.uk
  test-rp: https://test-rp-integration.cloudapps.digital/test-rp
  idps:
    Stub Country: https://ida-stub-idp-integration.cloudapps.digital/eidas/stub-country/
    Stub Idp Demo One: https://idp-stub-integration.ida.digital.cabinet-office.gov.uk/stub-idp-demo-one/
    Stub Idp Demo Two: https://idp-stub-integration.ida.digital.cabinet-office.gov.uk/stub-idp-demo-two/
    Stub Idp Disconnected: https://idp-stub-integration.ida.digital.cabinet-office.gov.uk/stub-idp-disconnected/